### PR TITLE
Test shared draw

### PR DESCRIPTION
**Pull request by dnaranjo89**
That's testing pretty much everything in the shared draw:
* Create a shared *Random Number* draw
* Give it a title
* Invite a user when creating it
* Check that the interface fits for owner and guest
 * Toss button
 * Schedule toss button
 * Settings button
 * Subscribe button
* Check that chat is blurred when the user does not have an alias
* Check access to the chat
* The messages are sent correctly
* Disable/Enable chat
* Draw fields are read only
* Update draw fields are automatically reflected in other windows
* Invite users from the settings panel
* Toss

**Don't merge**, just forgot a couple of things to test:
* Schedule toss?
* Let me know if I'm missing something

### CODE REVIEW

**Comment by Mariocj89** [comment]
Would be better to have separate tests for different functionalities within the draw as if this test fail we dont get much information, but it is a good start though.

**Comment by Mariocj89** [comment]
Moreover, check https://travis-ci.org/etcaterva/EchaloASuerte/jobs/88846615#L438 we need the tests to wait for the last response or they log the error at the end of the test.

**Comment by dnaranjo89** [comment]
logging in two browsers, creating shared draw, accessing, making changes... It's a long process and selenium tests take a while...

Splitting the test implies repeating all this process and increasing the time spent to run it.

**Comment by Mariocj89** [comment]
ok, we actually have unit tests for small func. Let me know when it can get merged as you said not to merge it in the commit. btw, you have the QA checklist if you need inspiration :)

**Pull request merged**
