### PR TITLE
Add translation

### PR DESCRIPTION
**Pull request by dnaranjo89**

### CODE REVIEW

**Comment by Mariocj89** [comment]
Con este cambio Cambia's lo que salesl buscar la web en google... :s

**Comment by dnaranjo89** [comment]
Yes but it doesn't make sense that when you get the result PickForMe in Google, the description is in Spanish. 

This also happens when you share the link on any social network: http://www.awesomescreenshot.com/image/417781/c14e43d1251a69df712e353906bbc555

How should we approach this?

**Comment by Mariocj89** [comment]
Given that today a higher number of users are spanish, lets not change it to english. Look in google for the answer :)

**Comment by dnaranjo89** [comment]
I agree, close the PR and open a new issue #413

**Pull request closed without merging**
