### PR TITLE
Spin on the first result

### LINKED ISSUE #617: Toss button in coin draw dissappears
When you toss in coin draw the toss button dissappears.

Not sure if this only happens in small screens.

### PR DESCRIPTION
**Pull request by Mariocj89**
Fixes #617

### CODE REVIEW

**Comment by dnaranjo89** [comment]
the secondary effect of this is that when you access a shared draw with results (or a draw stored in favourites) it will be animated, giving the idea that it has been just tossed. 
And it will do the same every time is reloaded showing the same result.... weird behaviour if we are give randomness...

**Comment by Mariocj89** [comment]
It is better than now that it judt dont work

**Comment by dnaranjo89** [comment]
then add it also to the coin and dice :)

**Comment by Mariocj89** [comment]
Updated

**Pull request merged**
